site_name: 我的博客
site_url: https://wanghaolong.github.io
site_description: PlantUML 博客
repo_url: https://github.com/wanghaolong/wanghaolong.github.io

theme:
  name: material

markdown_extensions:
  - pymdownx.superfences
  - plantuml_markdown:
      server: https://www.plantuml.com/plantuml

nav:
  - 首页: index.md
  - PlantUML分享: PlantUML分享/PlantUML分享.md
