name: Deploy MkDocs with PlantUML

on:
  push:
    branches:
      - main  # 在推送到 main 分支时触发部署

# 设置 GITHUB_TOKEN 的权限
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Step 2: 设置 Python 环境
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    # Step 3: 安装 MkDocs 和扩展插件
    - name: Install dependencies
      run: |
        pip install mkdocs-material
        pip install pymdown-extensions
        pip install plantuml-markdown

    # Step 4: 配置 Git
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # Step 5: 检查分支状态
    - name: Check branches
      run: |
        echo "Current branch:"
        git branch --show-current
        echo "All branches:"
        git branch -a

    # Step 6: 构建并部署 MkDocs（添加详细日志）
    - name: Build and Deploy
      run: |
        mkdocs gh-deploy --force --verbose

    # Step 7: 验证部署
    - name: Verify deployment
      run: |
        echo "Checking gh-pages branch..."
        git checkout gh-pages
        ls -la
        echo "Current directory content:"
        pwd